name: Python Package using Conda
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt; fi
      - name: SignIn
        run: |
          python ./auto_wb_qq.py
